CoffeeHouse/CoffeeHouse/Models/Staff.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace CoffeeHouse.Models
{
    public class Staff
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int IdStaff { get; set; }
        public string FullName { get; set; }
        public DateTime Birthday { get; set; }  
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Position { get; set; }
    }
}

CoffeeHouse/CoffeeHouse/Areas/Admin/Controllers/StaffController.cs
using CoffeeHouse.Data;
using CoffeeHouse.Models;
using Microsoft.AspNetCore.Mvc;

namespace CoffeeHouse.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class StaffController : Controller
    {
        private CoffeeHouseContext db;
        public StaffController(CoffeeHouseContext db)
        {
            this.db = db;
        }
        public IActionResult Index(int? page)
        {
            var staffs = db.Staff.ToList();
            // Paging

            if (page > 0)
            {
                page = page;
            }
            else
            {
                page = 1;
            }

            int limit = 2; // Số sản phẩm trong 1 trang
            int start = (int)(page - 1) * limit;
            int totalProducts = staffs.Count();

            ViewBag.totalProducts = totalProducts;
            ViewBag.pageCurrent = page;

            float numberPage = (float)totalProducts / limit;
            ViewBag.numberPage = (int)Math.Ceiling(numberPage);
            var dataStaff = staffs.OrderBy(c => c.IdStaff).Skip(start).Take(limit); ;
            return View(dataStaff);
        }

        // Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Staff staff)
        {
            if (ModelState.IsValid)
            {
                db.Staff.Add(staff);
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(staff);
        }

        // Edit
        public IActionResult Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staff = db.Staff.Find(id);
            if (staff == null)
            {
                return NotFound();
            }
            return View(staff);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Staff staff)
        {
            if (ModelState.IsValid)
            {
                db.Update(staff);
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(staff);
        }

        // Delete
        public IActionResult Delete(int id)
        {
            var staff = db.Staff.Find(id);
            if (staff == null)
            {
                return NotFound();
            }
            return View(staff);

        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var staff = db.Staff.Find(id);
            if (staff == null)
            {
                return NotFound();
            }

            db.Staff.Remove(staff);
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

CoffeeHouse/CoffeeHouse/Areas/Admin/Views/Staff/Create.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@model Staff
<div class="ms-2 mx-2">
    <h1 style="margin-top: 50px; text-align: center">Create</h1>
    <div asp-validation-summary="All" class="text-danger"></div>
    <form asp-controller="Satff" asp-action="Create" method="post" class="mt-3" style="width: 60%;
        margin: 0 auto; padding-top: 30px">
        <div style="margin-top:10px" class="form-group row">
            <label asp-for="IdStaff" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="IdStaff" class="form-control" placeholder="Id">
            </div>
            <span asp-validation-for="IdStaff" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <label asp-for="FullName" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="FullName" class="form-control" placeholder="FullName">
            </div>
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <label asp-for="Email" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Email" class="form-control" placeholder="Email">
            </div>
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <label asp-for="Birthday" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Birthday" class="form-control" placeholder="Birthday">
            </div>
            <span asp-validation-for="Birthday" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <label asp-for="Address" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Address" class="form-control" placeholder="Address">
            </div>
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <label asp-for="Phone" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Phone" class="form-control" placeholder="Phone">
            </div>
            <span asp-validation-for="Phone" class="text-danger"></span>
        </div>

        <div style="margin-top:10px" class="form-group row">
            <div class="col-sm-10" style="padding: 20px 0">
                <button type="submit" class="btn btn-primary" style="padding: 10px 40px">Create</button>
            </div>
        </div>
    </form>
</div> 

CoffeeHouse/CoffeeHouse/Areas/Admin/Views/Staff/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@model Staff
<div class="ms-2 mx-2">
    <h1>Delete</h1>
    <h3>Are you sure you want to delete this?</h3>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model. IdStaff)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model. IdStaff)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dt class="col-sm-10">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model. Email)
        </dd>
        <dd class="col-sm-2">
            @Html.DisplayFor(model => model. Birthday)
        </dd>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model. Birthday)
        </dd>
        <dd class="col-sm-2">
            @Html.DisplayFor(model => model. Address)
        </dd>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model. Address)
        </dd>
        <dd class="col-sm-2">
            @Html.DisplayFor(model => model. Phone)
        </dd>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model. Phone)
        </dd>
    </dl>
    <form asp-action="Delete">
        <input type="hidden" asp-for="@Model.IdStaff" />
        <input type="submit" value="Delete" class="btn btn-danger" /> | <a asp-action="Index">Back to List</a>
    </form>
</div>

CoffeeHouse/CoffeeHouse/Areas/Admin/Views/Staff/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@model Staff
<div class="ms-2 mx-2">
    <h1 style="margin-top: 50px; text-align: center">Edit</h1>
    <div asp-validation-summary="All" class="text-danger"></div>
    <form asp-controller="Staff" asp-action="Edit" asp-route-id="@Model.IdStaff" method="post" class="mt-3" style="width: 60%;
        margin: 0 auto; padding-top: 30px">
        <input type="hidden" asp-for="IdStaff" />
        <div style="margin-top:10px" class="form-group row">
            <label asp-for="IdStaff" class="col-sm-2 col-form-label"></label> <div class="col-sm-10">
                <input asp-for="IdStaff" class="form-control" placeholder="Id">
            </div>
            <span asp-validation-for="IdStaff" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <label asp-for="FullName" class="col-sm-2 col-form-label"></label> <div class="col-sm-10">
                <input asp-for="FullName" class="form-control" placeholder="Name">
            </div>
            <span asp-validation-for="FullName" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <label asp-for="Email" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Email" class="form-control" placeholder="Email">
            </div>
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <label asp-for="Birthday" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Birthday" class="form-control" placeholder="Birthday">
            </div>
            <span asp-validation-for="Birthday" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <label asp-for="Address" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Address" class="form-control" placeholder="Address">
            </div>
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <label asp-for="Phone" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Phone" class="form-control" placeholder="Phone">
            </div>
            <span asp-validation-for="Phone" class="text-danger"></span>
        </div>

        <div style="margin-top:10px" class="form-group row">
            <div class="col-sm-10" style="padding: 20px 0">
                <button type="submit" class="btn btn-primary" style="padding: 10px 40px">Edit</button>
            </div>
        </div>

    </form>
</div> 

CoffeeHouse/CoffeeHouse/Areas/Admin/Views/Staff/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@model IEnumerable<Staff>
<div id="content">
    <h3 style="margin-top: 50px; text-align: center; padding-bottom: 50px">Staff List</h3>
    <table class="table table-striped" style="margin: 0 auto; width: 80%">
        <thead style="background-color: black; color: white">
            <tr>
                <th>ID</th>
                <th>Fullname</th>
                <th>Email</th>
                <th>Birthđay</th>
                <th>Address</th>
                <th>Phone</th>
                <th>Position</th>
                <th>Function</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var s in Model)
            {
                <tr>
                    <td>@s.IdStaff</td>
                    <td>@s.FullName</td>
                    <td>@s.Email</td>
                    <td>@s.Birthday</td>
                    <td>@s.Address</td>
                    <td>@s.Phone</td>
                    <td>@s.Position</td>
                    <td>
                        <a style="background-color: green; text-decoration: none; color: white; padding: 5px 10px" asp-action="Edit" asp-route-id="@s.IdStaff">Edit</a>
                        <a style="background-color: red; text-decoration: none; color: white; padding: 5px 10px" asp-action="Delete" asp-route-id="@s.IdStaff">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="pagination">
        <div aria-label="Page navigation example">
            <ul class="pagination">
                @{
                    int numberPage = ViewBag.numberPage;
                    int pageCurrent = ViewBag.pageCurrent;

                    if (pageCurrent > 1)
                    {
                        int prePage = pageCurrent - 1;
                        <li class="page-item">
                            <a class="page-link" href="?page=@prePage" aria-label="Previous">
                                <span aria-hidden="true">
                                    ‹
                                </span>
                            </a>
                        </li>
                    }

                    int i;
                    for (i = 1; i <= numberPage; i++)
                    {
                        if (i == pageCurrent)
                        {
                            <li class="page-item active"><a class="page-link" href="?page=@i">@i</a></li>
                        }
                        else
                        {
                            <li class="page-item"><a class="page-link" href="?page=@i">@i</a></li>
                        }
                    }

                    if (pageCurrent > 1 && pageCurrent < numberPage)
                    {
                        int nextPage = pageCurrent + 1;
                        <li class="page-item">
                            <a class="page-link" href="?page=@nextPage" aria-label="Next">
                                <span aria-hidden="true">
                                    ›
                                </span>
                            </a>
                        </li>
                    }
                }
            </ul>
        </div>
    </div>
    <a asp-action="Create" class="btn btn-primary" style="padding: 10px; margin-left: 120px">Create New Staff</a>
</div>