CoffeeHouse/CoffeeHouse/Models/Menu.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace CoffeeHouse.Models
{
    public class Menu
    {
        public Menu()
        {
            Image = "~/images_icon/menu/list_menu/mn1.jpg";
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public string Id { get; set; }

        public string IdCategory { get; set; }
        [ForeignKey("IdCategory")]
        [ValidateNever]
        public Category Category { get; set; }

        public string Name { get; set; }
        public float Price { get; set; }
        public string Image { get; set; }

        [NotMapped]
        public IFormFile ImageUpload { get; set; }
    }
}

CoffeeHouse/CoffeeHouse/Areas/Admin/Controllers/MenuController.cs
using CoffeeHouse.Data;
using CoffeeHouse.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace CoffeeHouse.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MenuController : Controller
    {
        private CoffeeHouseContext db;
        public MenuController(CoffeeHouseContext db)
        {
            this.db = db;
        }
        public IActionResult Index(int? page)
        {
            var menu = db.Menu.Include(c => c.Category).ToList();

            // Paging

            if (page > 0)
            {
                page = page;
            }
            else
            {
                page = 1;
            }

            int limit = 4; // Số sản phẩm trong 1 trang
            int start = (int)(page - 1) * limit;
            int total = menu.Count();

            ViewBag.total = total;
            ViewBag.pageCurrent = page;

            float numberPage = (float)total / limit;
            ViewBag.numberPage = (int)Math.Ceiling(numberPage);
            var data = menu.OrderBy(c => c.Id).Skip(start).Take(limit); ;
            return View(data);
        }

        // Create
        public IActionResult Create()
        {
            Menu menu = new Menu();
            ViewBag.IdCategory = new SelectList(db.Categories, "IdCategory", "Name");
            return View(menu);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Menu menu)
        {
            if (ModelState.IsValid)
            {
                if (menu.ImageUpload != null)
                {
                    string uniqueFileName = Guid.NewGuid().ToString() + "_" + menu.ImageUpload.FileName;
                    string uploadPath = Path.Combine("~/images_icon/menu/list_menu/", uniqueFileName);
                    string absolutePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images_icon/menu/list_menu", uniqueFileName);

                    using (var stream = new FileStream(absolutePath, FileMode.Create))
                    {
                        await menu.ImageUpload.CopyToAsync(stream);
                    }

                    menu.Image = uploadPath; // Lưu đường dẫn đến tệp mới với tên mới
                }
                db.Menu.Add(menu);
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.IdCategory = new SelectList(db.Categories, "IdCategory", "Name");
            return View(menu);
        }

        // Edit
        public IActionResult Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menu = db.Menu.Find(id);
            if (menu == null)
            {
                return NotFound();
            }
            ViewBag.IdCategory = new SelectList(db.Categories, "IdCategory", "Name");
            return View(menu);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Menu menu)
        {
            if (ModelState.IsValid)
            {
                if (menu.ImageUpload != null)
                {
                    string uniqueFileName = Guid.NewGuid().ToString() + "_" + menu.ImageUpload.FileName;
                    string uploadPath = Path.Combine("~/images_icon/menu/list_menu/", uniqueFileName);
                    string absolutePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images_icon/menu/list_menu", uniqueFileName);

                    using (var stream = new FileStream(absolutePath, FileMode.Create))
                    {
                        await menu.ImageUpload.CopyToAsync(stream);
                    }

                    menu.Image = uploadPath; // Lưu đường dẫn đến tệp mới với tên mới
                }
                db.Update(menu);
                db.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.IdCategory = new SelectList(db.Categories, "IdCategory", "Name");
            return View(menu);
        }

        // Delete
        public IActionResult Delete(string id)
        {
            var menu = db.Menu.Include(pro => pro.Category).FirstOrDefault(c => c.Id == id);
            if (menu == null)
            {
                return NotFound();
            }
            return View(menu);

        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(string id)
        {
            var menu = db.Menu.Find(id);
            if (menu == null)
            {
                return NotFound();
            }

            db.Menu.Remove(menu);
            db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

CoffeeHouse/CoffeeHouse/Controllers/MenuController.cs
using CoffeeHouse.Data;
using CoffeeHouse.Models;
using Microsoft.AspNetCore.Mvc;

namespace CoffeeHouse.Controllers
{
    public class MenuController : Controller
    {
        public CoffeeHouseContext db;
        public MenuController(CoffeeHouseContext db)
        {
            this.db = db;
        }
        public IActionResult Menu(int? page)
        {
            var listMenu = db.Menu.ToList();

            if (page > 0)
            {
                page = page;
            }
            else
            {
                page = 1;
            }

            int limit = 6; // Số sản phẩm trong 1 trang
            int start = (int)(page - 1) * limit;
            int total = listMenu.Count();

            ViewBag.totalProducts = total;
            ViewBag.pageCurrent = page;

            float numberPage = (float)total / limit;
            ViewBag.numberPage = (int)Math.Ceiling(numberPage);
            var dataProducts = listMenu.OrderBy(c => c.Id).Skip(start).Take(limit); ;
            return View(dataProducts);
        }
        public IActionResult MenuProducts(string id, int? page) 
        {
            List<Menu> lst = db.Menu.Where(x => x.IdCategory == id).OrderBy(x => x.Name).ToList();

            if (page > 0)
            {
                page = page;
            }
            else
            {
                page = 1;
            }

            int limit = 3; // Số sản phẩm trong 1 trang
            int start = (int)(page - 1) * limit;
            int total = lst.Count();

            ViewBag.total = total;
            ViewBag.pageCurrent = page;

            float numberPage = (float)total / limit;
            ViewBag.numberPage = (int)Math.Ceiling(numberPage);
            var data = lst.OrderBy(c => c.Id).Skip(start).Take(limit); ;
            return View(data);
        }
    }
}

CoffeeHouse/CoffeeHouse/Areas/Admin/Views/Menu/Create.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@model Menu
<div class="ms-2 mx-2">
    <h1 style="margin-top: 50px; text-align: center">Create</h1>
    <div asp-validation-summary="All" class="text-danger"></div>
    <form asp-controller="Menu" asp-action="Create" method="post" asp-route-id="@Model.Id" enctype="multipart/form-data" style="width: 60%;
        margin: 0 auto; padding-top: 30px">
        <div style="margin-top:10px" class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Id" class="form-control" placeholder="Id">
            </div>
            <span asp-validation-for="Id" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Name" class="form-control" placeholder="FullName">
            </div>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="Category" class="col-sm-2 col-form-label"></label> <div class="col-sm-10">
                <select asp-for="IdCategory" class="custom-select mr-sm-2"
                        asp-items="@ViewBag. IdCategory"></select>

            </div>
            <span asp-validation-for="IdCategory" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <label asp-for="Price" class="col-sm-2 col-form-label"></label> <div class="col-sm-10">
                <input asp-for="Price" class="form-control" placeholder="Price">
            </div>
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <label asp-for="Image" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <img src="@Url.Content(Model.Image)" style="height: 200px; width: 200px; margin: 10px" id="previewImage" />
                <input type="file" name="ImageUpload" onchange="ShowImage(this, document.getElementById('previewImage'))" />
                <input asp-for="Image" class="form-control" placeholder="Image">
            </div>
            <span asp-validation-for="Image" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <div class="col-sm-10" style="padding: 20px 0">
                <button type="submit" class="btn btn-primary" style="padding: 10px 40px">Create</button>
            </div>
        </div>
    </form>
</div> 

CoffeeHouse/CoffeeHouse/Areas/Admin/Views/Menu/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@model Menu
<div class="ms-2 mx-2">
    <h1>Delete</h1>
    <h3>Are you sure you want to delete this?</h3>
    <h4>Menu</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model. Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model. Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model. Category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model. Category.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model. Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model. Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class="col-sm-10">
            <img src="@Url.Content(Model.Image)" alt="Product Image" style="max-width: 100px; max-height: 100px;" />
        </dd>
    </dl>
    <form asp-action="Delete">
        <input type="hidden" asp-for="@Model.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> | <a asp-action="Index">Back to List</a>
    </form>
</div>

CoffeeHouse/CoffeeHouse/Areas/Admin/Views/Menu/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@model Menu
<div class="ms-2 mx-2">
    <h1 style="margin-top: 50px; text-align: center">Edit</h1>
    <div asp-validation-summary="All" class="text-danger"></div>
    <form asp-controller="Menu" asp-action="Edit" asp-route-id="@Model.Id" method="post" enctype="multipart/form-data" class="mt-3" style="width: 60%;
        margin: 0 auto; padding-top: 30px">
        <input type="hidden" asp-for="Id" />
        <div style="margin-top:10px" class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label> <div class="col-sm-10">
                <input asp-for="Id" class="form-control" placeholder="Id">
            </div>
            <span asp-validation-for="Id" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <label asp-for="Name" class="col-sm-2 col-form-label"></label> <div class="col-sm-10">
                <input asp-for="Name" class="form-control" placeholder="Name">
            </div>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div style="margin-top:7px" class="form-group row">
            <label asp-for="IdCategory" class="col-sm-2 col-form-label"></label> <div class="col-sm-10">
                <select asp-for="IdCategory" class="custom-select mr-sm-2"
                        asp-items="@ViewBag. IdCategory"></select>

            </div>
            <span asp-validation-for="IdCategory" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <label asp-for="Price" class="col-sm-2 col-form-label"></label> <div class="col-sm-10">
                <input asp-for="Price" class="form-control" placeholder="Price">
            </div>
            <span asp-validation-for="Price" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <label asp-for="Image" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <img src="@Url.Content(Model.Image)" style="height: 200px; width: 200px; margin: 10px" id="previewImage" />
                <input type="file" name="ImageUpload" onchange="ShowImage(this, document.getElementById('previewImage'))" />
                <input asp-for="Image" class="form-control" placeholder="Image">
            </div>
            <span asp-validation-for="Image" class="text-danger"></span>
        </div>
        <div style="margin-top:10px" class="form-group row">
            <div class="col-sm-10" style="padding: 20px 0">
                <button type="submit" class="btn btn-primary" style="padding: 10px 40px">Edit</button>
            </div>
        </div>
    </form>
</div> 

CoffeeHouse/CoffeeHouse/Areas/Admin/Views/Menu/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@model IEnumerable<Menu>
<div id="content">
    <div id="container">
        <h3 style="margin-top: 50px; text-align: center; padding-bottom: 50px">List Menu</h3>
        <table id="dataTable" class="table table-striped" style="margin: 0 auto; width: 95%">
            <thead style="background-color: black; color: white" id="dataTable">
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Catgory</th>
                    <th>Price</th>
                    <th>Image</th>
                    <th>Function</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var s in Model)
                {
                    <tr>
                        <td>@s.Id</td>
                        <td>@s.Name</td>
                        <td>@s.Category.Name</td>
                        <td>$@s.Price</td>
                        <th>
                            <img src="@Url.Content(s.Image)" alt="Product Image" style="max-width: 100px; max-height: 100px;" />
                        </th>
                        <td>
                            <a style="background-color: green; text-decoration: none; color: white; padding: 5px 10px" asp-action="Edit" asp-route-id="@s.Id">Edit</a>
                            <a style="background-color: red; text-decoration: none; color: white; padding: 5px 10px" asp-action="Delete" asp-route-id="@s.Id">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="pagination">
        <div aria-label="Page navigation example">
            <ul class="pagination">
                @{
                    int numberPage = ViewBag.numberPage;
                    int pageCurrent = ViewBag.pageCurrent;

                    if (pageCurrent > 1)
                    {
                        int prePage = pageCurrent - 1;
                        <li class="page-item">
                            <a class="page-link" href="?page=@prePage" aria-label="Previous">
                                <span aria-hidden="true">
                                    ‹
                                </span>
                            </a>
                        </li>
                    }

                    int i;
                    for (i = 1; i <= numberPage; i++)
                    {
                        if (i == pageCurrent)
                        {
                            <li class="page-item active"><a class="page-link" href="?page=@i">@i</a></li>
                        }
                        else
                        {
                            <li class="page-item"><a class="page-link" href="?page=@i">@i</a></li>
                        }
                    }

                    if (pageCurrent > 1 && pageCurrent < numberPage)
                    {
                        int nextPage = pageCurrent + 1;
                        <li class="page-item">
                            <a class="page-link" href="?page=@nextPage" aria-label="Next">
                                <span aria-hidden="true">
                                    ›
                                </span>
                            </a>
                        </li>
                    }
                }
            </ul>
        </div>
    </div>
    <br />
    <a asp-action="Create" class="btn btn-primary" style="margin-top: 20px; padding: 10px; margin-left: 50px">Create New Products</a>
</div>